language: php

php:
    - 7.2

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - travis_retry composer self-update
    - pecl -q install mongo && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

install:
    - composer install --prefer-dist --no-interaction
    - stty cols 120 && composer show

script:
    - composer test-all
