language: php

php:
    - 7.2

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - travis_retry composer self-update
    - echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    - composer install --prefer-dist --no-interaction
    - stty cols 120 && composer show

script:
    - composer test-all
