version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - '2006:80'
        volumes:
            - ./public:/public
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx:/var/log/nginx
        links:
            - php
    php:
        build: ./docker/php
        volumes:
            - .:/app
        working_dir: /app
