version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - '2006:80'
        volumes:
            - ./public:/public
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx:/var/log/nginx
        links:
            - php
    php:
        build: ./docker/php
        volumes:
            - .:/app
        working_dir: /app
        links:
            - rabbitmq
        depends_on:
            - rabbitmq
    rabbitmq:
        image: rabbitmq:3-management
        hostname: 'rabbitmq'
        environment:
            RABBITMQ_DEFAULT_USER: rabbitmq
            RABBITMQ_DEFAULT_PASS: rabbitmq
        ports:
            - '15672:15672'
#            - '5672:5672'
        labels:
            NAME: rabbitmq
        volumes:
            - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
