version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - '2006:80'
        volumes:
            - ./public:/public
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx:/var/log/nginx
        links:
            - php
    php:
        build: ./docker/php
        volumes:
            - .:/app
        working_dir: /app
        links:
            - queue

    queue:
        image: rabbitmq:3-management
        hostname: 'queue'
        environment:
            RABBITMQ_ERLANG_COOKIE: YWRUIFFVQNLSCMAOHIMQ
            RABBITMQ_DEFAULT_USER: rabbitmq
            RABBITMQ_DEFAULT_PASS: rabbitmq
            RABBITMQ_DEFAULT_VHOST: '/'
        ports:
            - '15672:15672'
            - '5672:5672'
        labels:
            NAME: queue
        volumes:
            - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
