version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - '2006:80'
        volumes:
            - ./public:/public
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        build: ./docker/php
        volumes:
            - .:/app
        working_dir: /app
        links:
            - rabbitmq
            - mongodb
        depends_on:
            - rabbitmq
            - mongodb
    queue:
        build: ./docker/php
        volumes:
            - .:/app
        working_dir: /app/queue
        links:
            - rabbitmq
            - mongodb
        depends_on:
            - rabbitmq
            - mongodb
        command:
            - /app/queue/init-queue.sh
    rabbitmq:
        image: rabbitmq:3-management
        hostname: 'rabbitmq'
        environment:
            RABBITMQ_DEFAULT_USER: rabbitmq
            RABBITMQ_DEFAULT_PASS: rabbitmq
        ports:
            - '15672:15672'
        labels:
            NAME: rabbitmq
        volumes:
            - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    mongodb:
        image: mongo:3
        container_name: mongodb
        ports:
          - '27017:27017'
