version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - '2006:80'
        volumes:
            - ./public:/public
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
